### ISSUE TITLE
June Carto Rebase

### ISSUE THREAD

**Issue by jjmata** [splashblot/dronedb#28]
Every month we should:

  - [x] Fast-forward the master branch to pick up latest changes
  - [x] Read [NEWS.md](https://github.com/CartoDB/cartodb/blob/master/NEWS.md) in all relevant repos ([here](https://github.com/CartoDB/cartodb.js/blob/develop/NEWS.md) and [here](https://github.com/CartoDB/crankshaft/blob/develop/NEWS.md) and [here](https://github.com/CartoDB/Windshaft-cartodb/blob/master/NEWS.md) and [here](https://github.com/CartoDB/CartoDB-SQL-API/blob/master/NEWS.md) as well ... probably more) and adjust as necessary
  - [x] Pick up any necessary changes to config files ([app_config.yml](https://github.com/cartodb/cartodb/blob/master/config/app_config.yml.sample) and [here](https://github.com/CartoDB/CartoDB-SQL-API/tree/master/config/environments) and [here](https://github.com/CartoDB/Windshaft-cartodb/tree/master/config/environments) as well)
  - [ ] Check `/diagnosis` and fix any regressions
  - [ ] Peek at sverhoeven's repo for any lessons learned
  - [ ] Rebase the [tileo branch](https://github.com/splashblot/dronedb/tree/tileo)
  - [x] Rebase any other bits that we are working on but have not made the [tileo branch](https://github.com/splashblot/dronedb/tree/tileo) yet ([tileo-devops](https://github.com/splashblot/dronedb/tree/tileo-devops) tends to have stuff "in progress" that hasn't been merged to [tileo](https://github.com/splashblot/dronedb/tree/tileo) yet)
  - [x] Deploy the sucker to `alpha.tileo.co` and test some of the sample data visualizations! ✌️ 
  - [x] Rebase `tileo-develop` for new/WIP feature work
  - [ ] Promote "the build" to `beta.tileo.co`
  - [x] Promote "the build" to `smartrural.tileo.co`

May-specific tasks (carry-over!):

  - [ ] Make sure infowindows work in `*.tileo.co`
  - [ ] Pick up dataservices configuration example, see [here](https://github.com/CartoDB/cartodb/commit/bdb202cfc53d50316698331bc37096617af8fe56)
  - [x] Re-wire DO config up so datasets show up again
  - [ ] Add the `crankshaft` extension to the `template_postgis` database as per [this suggestion](https://groups.google.com/forum/#!topic/cartodb/iJrZP4Hl0sk) 
  - [ ] Fix/upload NPM package to use for uploading data to `tileo.co` instead of `carto.com`, see [here](https://github.com/splashblot/cartodb-nodejs/commit/af6292c5dd2e23258e57c2b9e5bca54222a9f6c1)
  - [ ] (optional) https://github.com/sverhoeven/docker-cartodb/commit/bbf2c543256ca4ef0f84099b9a680ded6108e756
Starting on this next week, other items to consider this month:
  - [x] (optional) Try to deploy to a more powerful machine to improve performance _See SoftLayer!_
  - [x] (optional) Try to enable / force `HTTP/2` _Works in SoftLayer!_

June-specific tasks:

  - [ ] (optional) Check to see if DO frontend landed (see https://github.com/CartoDB/cartodb/issues/11663 and https://github.com/CartoDB/cartodb/milestone/135)
  - [ ] Re-brand email templates & Org pages

**Comment by jjmata** [comment]
Watch out for these items from `NEWS.md`:

  - [x] `create_dev_user` semantics: https://github.com/CartoDB/cartodb/pull/12187
  - [ ] Org notifications: https://github.com/CartoDB/cartodb/issues/11850 (could be used for mobile app alarms)
  - [ ] 'SQL function' analysis: https://github.com/CartoDB/cartodb/issues/12018
  - [ ] Multiple file upload: https://github.com/CartoDB/cartodb/issues/11952
  - [ ] Infowindow fix: https://github.com/CartoDB/cartodb/issues/12167
  - [ ] Pluggable frontends: https://github.com/CartoDB/cartodb/issues/11022

**Comment by jjmata** [comment]
Started on this yesterday and cut a few new branches  so that nothing else would be impacted:
  * `tileo-june2017` will become `tileo` soon-ish
  * `tileo-develop-june2017`will become `tileo-develop` soon-ish as well

A lot of branches where rebased as well, and a few of them fixed to make sure they are green in TravisCI! 👍 

Will keep you posted here.

/cc @apercas and @MariaCheca to keep them in the loop

**Comment by apercas** [comment]
Cooooool!

**Comment by jjmata** [comment]
Lots of progress yesterday, and most of this is done.  We area ready to move to the new branches and delete the existing ones!  Plus most stuff is starting to pass on TravisCI! 👍 

👏  👏  👏  to @MariaCheca y @apercas who burnt the midnight oil last night getting this stuff out!

**Comment by jjmata** [comment]
Closing this and moving future work to https://github.com/splashblot/dronedb/issues/31.
