### ISSUE TITLE
August Carto Rebase

### ISSUE THREAD

**Issue by jjmata** [splashblot/dronedb#31]
Every month we should:

  - [x] Fast-forward the master branch to pick up latest changes
  - [x] Read [NEWS.md](https://github.com/CartoDB/cartodb/blob/master/NEWS.md) in all relevant repos ([here](https://github.com/CartoDB/cartodb.js/blob/develop/NEWS.md) and [here](https://github.com/CartoDB/crankshaft/blob/develop/NEWS.md) and [here](https://github.com/CartoDB/Windshaft-cartodb/blob/master/NEWS.md) and [here](https://github.com/CartoDB/CartoDB-SQL-API/blob/master/NEWS.md) as well ... probably more) and adjust as necessary
  - [x] Pick up any necessary changes to config files ([app_config.yml](https://github.com/cartodb/cartodb/blob/master/config/app_config.yml.sample) and [here](https://github.com/CartoDB/CartoDB-SQL-API/tree/master/config/environments) and [here](https://github.com/CartoDB/Windshaft-cartodb/tree/master/config/environments) as well)
  - [x] Check `/diagnosis` and fix any regressions
  - [ ] Peek at sverhoeven's repo for any lessons learned
  - [x] Rebase the [tileo branch](https://github.com/splashblot/dronedb/tree/tileo)
  - [x] Rebase any other bits that we are working on but have not made the [tileo branch](https://github.com/splashblot/dronedb/tree/tileo) yet ([tileo-devops](https://github.com/splashblot/dronedb/tree/tileo-devops) tends to have stuff "in progress" that hasn't been merged to [tileo](https://github.com/splashblot/dronedb/tree/tileo) yet)
  - [x] Rebase `tileo-develop` for new/WIP feature work
  - [x] Promote "the build" to `tileo-beta.co`
  - [x] Promote "the build" to `tileo.co`

May-specific tasks (carry-over!):

  - [x] Make sure infowindows work in `*.tileo.co`
  - [x] Pick up dataservices configuration example, see [here](https://github.com/CartoDB/cartodb/commit/bdb202cfc53d50316698331bc37096617af8fe56)
  - [x] Add the `crankshaft` extension to the `template_postgis` database as per [this suggestion](https://groups.google.com/forum/#!topic/cartodb/iJrZP4Hl0sk) 
  - [ ] Fix/upload NPM package to use for uploading data to `tileo.co` instead of `carto.com`, see [here](https://github.com/splashblot/cartodb-nodejs/commit/af6292c5dd2e23258e57c2b9e5bca54222a9f6c1)
  - [ ] (optional) https://github.com/sverhoeven/docker-cartodb/commit/bbf2c543256ca4ef0f84099b9a680ded6108e756

June-specific tasks (carry-over!):

  - [ ] (optional) Check to see if all DO changes landed (see issues 11663 and 12682, plus https://github.com/CartoDB/cartodb/milestone/135)
  - [x] Re-brand email templates & Org pages

**Comment by jjmata** [comment]
Interesting items from June review of `NEWS.md`:

  - [x] `create_dev_user` semantics: https://github.com/CartoDB/cartodb/pull/12187
  - [ ] Org notifications: https://github.com/CartoDB/cartodb/issues/11850 (could be used for mobile app alarms)
  - [ ] 'SQL function' analysis: https://github.com/CartoDB/cartodb/issues/12018
  - [ ] Multiple file upload: https://github.com/CartoDB/cartodb/issues/11952
  - [ ] Layers upgrade message: https://github.com/CartoDB/cartodb/issues/12167
  - [ ] Pluggable frontends: https://github.com/CartoDB/cartodb/issues/11022

**Comment by jjmata** [comment]
Monthly might be too aggressive, we shall see.  Maybe quarterly is a better cadence, or "when something of interest lands" could work too ... ;-)  Thoughts @apercas and @MariaCheca?

**Comment by jjmata** [comment]
For instance, we could start "cherry-picking" interesting features and delaying the big rebase to every 3 months or so when something big happens like "new Mapnik" was, right?

Look at this one as a good cherry pick candidate:

  * https://github.com/CartoDB/cartodb/issues/12421

**Comment by jjmata** [comment]
Tried to close this yesterday, but the rebase breaks widgets.  Working with @apercas today to get a new `cartodb.js` branch that completes this work.

**Comment by jjmata** [comment]
Infowindows now work everywhere, @ivanprado!

(stupidest one-line configuration fix ever ... just needed the SSL port number explicitly stated in the config file)

**Comment by ivanprado** [comment]
¡¡¡Nice!!! :-D

**Comment by jjmata** [comment]
This was done a few weeks back.  Closing (and creating the new one for after Fruit Attraction ...)
