### ISSUE TITLE
Next Carto Rebase

### ISSUE THREAD

**Issue by jjmata** [splashblot/dronedb#61]
Every month we should:

  - [ ] Fast-forward the master branch to pick up latest changes
  - [ ] Read [NEWS.md](https://github.com/CartoDB/cartodb/blob/master/NEWS.md) in all relevant repos ([here](https://github.com/CartoDB/cartodb.js/blob/develop/NEWS.md) and [here](https://github.com/CartoDB/crankshaft/blob/develop/NEWS.md) and [here](https://github.com/CartoDB/Windshaft-cartodb/blob/master/NEWS.md) and [here](https://github.com/CartoDB/CartoDB-SQL-API/blob/master/NEWS.md) as well ... probably more) and adjust as necessary
  - [ ] Pick up any necessary changes to config files ([app_config.yml](https://github.com/cartodb/cartodb/blob/master/config/app_config.yml.sample) and [here](https://github.com/CartoDB/CartoDB-SQL-API/tree/master/config/environments) and [here](https://github.com/CartoDB/Windshaft-cartodb/tree/master/config/environments) as well)
  - [ ] Check `/diagnosis` and fix any regressions
  - [ ] Peek at sverhoeven's repo for any lessons learned
  - [ ] Rebase the [tileo branch](https://github.com/splashblot/dronedb/tree/tileo)
  - [ ] Rebase any other bits that we are working on but have not made the [tileo branch](https://github.com/splashblot/dronedb/tree/tileo) yet ([tileo-devops](https://github.com/splashblot/dronedb/tree/tileo-devops) tends to have stuff "in progress" that hasn't been merged to [tileo](https://github.com/splashblot/dronedb/tree/tileo) yet)
  - [ ] Rebase `tileo-develop` for new/WIP feature work
  - [ ] Promote "the build" to `tileo-beta.co`
  - [ ] Promote "the build" to `smartrural.tileo.co`

May-specific tasks (carry-over!):

  - [x] ~~Make sure infowindows work in `*.tileo.co`~~
  - [ ] Deploy new DO: dataservices, bigmetadata, etc.  See [here](https://github.com/CartoDB/cartodb/commit/bdb202cfc53d50316698331bc37096617af8fe56) and [here](https://github.com/splashblot/bigmetadata/blob/master/docker-compose.yml).
  - [x] ~~Add the `crankshaft` extension to the `template_postgis` database as per [this suggestion](https://groups.google.com/forum/#!topic/cartodb/iJrZP4Hl0sk)~~
  - [ ] Fix/upload NPM package to use for uploading data to `tileo.co` instead of `carto.com`, see [here](https://github.com/splashblot/cartodb-nodejs/commit/af6292c5dd2e23258e57c2b9e5bca54222a9f6c1)
  - [ ] (optional) https://github.com/sverhoeven/docker-cartodb/commit/bbf2c543256ca4ef0f84099b9a680ded6108e756

June-specific tasks (carry-over!):

  - [ ] (optional) Check to see if all DO changes landed (see issues 11663 and 12682, plus https://github.com/CartoDB/cartodb/milestone/135)
  - [x] ~~Re-brand email templates & Org pages~~

**Comment by jjmata** [comment]
Interesting items from previous reviews of `NEWS.md`:

  - [x] ~~`create_dev_user` semantics: https://github.com/CartoDB/cartodb/pull/12187~~
  - [ ] Org notifications: https://github.com/CartoDB/cartodb/issues/11850 (could be used for mobile app alarms)
  - [ ] 'SQL function' analysis: https://github.com/CartoDB/cartodb/issues/12018
  - [ ] Multiple file upload: https://github.com/CartoDB/cartodb/issues/11952
  - [ ] Layers upgrade message: https://github.com/CartoDB/cartodb/issues/12167
  - [ ] Pluggable frontends: https://github.com/CartoDB/cartodb/issues/11022

**Comment by jjmata** [comment]
Cherry pick candidate(s):

  * https://github.com/CartoDB/cartodb/issues/12421
